sudo: required

language: java

before_install:
  - chmod +x gradlew

jdk:
  - oraclejdk8
script:
  - gradle check
  - gradle build

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: zooplus-currency-converter
