spring:
  datasource:
    name:
    url: ${DATABASE_URL}
    username: ${DATABASE_URL_USER}
    password: ${DATABASE_URL_PASSWORD}
    platform: postgres
    initialization-mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: true
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  
currency-converter:
  api:
    host: https://openexchangerates.org/api
    key: 550a3ed01afa4160a89561adc05fbfa9
