spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

currency-converter:
  api:
    host: https://openexchangerates.org/api
    key: 550a3ed01afa4160a89561adc05fbfa9
