spring:
  datasource:
    url: jdbc:postgresql://Host:Port/DatabaseName?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    name:
    username: User
    password: Password
    platform: postgres
    initialization-mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: true
server:
  port: 8080
  
currency-converter:
  api:
    host: https://openexchangerates.org/api
    key: 550a3ed01afa4160a89561adc05fbfa9
