currency-converter:
  api:
    host: https://openexchangerates.org/api
    key: 550a3ed01afa4160a89561adc05fbfa9
server:
  port: 9090
spring:
  datasource:
    name: ''
    password: ''
    url: jdbc:h2:mem:zooplus;DB_CLOSE_DELAY=-1
    username: zooplus
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
