#-Dspring.profiles.active=dev
spring:
  datasource:
    name: ''
    password: ''
    url: jdbc:h2:mem:zooplus;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: zooplus
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false

server:
  port: 9090