spring:
  datasource:
    name:
    url: ${DATABASE_URL}
    username: ${DATABASE_URL_USER}
    password: ${DATABASE_URL_PASSWORD}
    platform: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: true
server:
  port: 8080
  
currency-converter:
  api:
    host: https://openexchangerates.org/api
    key: 550a3ed01afa4160a89561adc05fbfa9
